[package]
name = "mailgun46"
version = "0.1.0"
authors = ["Niclas Rosengren <niclas.rosengren@gmail.com>"]
edition = "2018"
description = """
# Mailgun46
An email client using Mailgun.

The domain to use for mail can be configured using env variables.

* `MAILGUN46_DOMAIN`: The domain to send with.
* `MAILGUN46_TOKEN`: The token to use, taken directly from the one retreived from Mailgun.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
reqwest = { version = "0.10.10" , features = [ "json" ] }
serde = { version = "1.0.123", features = [ "derive" ] }
serde_json = "1.0.62"

[dev-dependencies]
anyhow = "1.0.38"
tokio = { version ="0.2.25", features = [ "rt-threaded", "macros" ] }
serde_json = "1.0.62"
wiremock = "0.5.0"
