[package]
name = "mailer46"
version = "0.1.0"
authors = ["Niclas Rosengren <niclas.rosengren@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
reqwest = { version = "0.10.10" , features = [ "json" ]}
serde = { version = "1.0.123", features = [ "derive" ] }

[dev-dependencies]
tokio = { version ="0.2.25", features = [ "rt-threaded", "macros" ] }
serde_json = "1.0.62"
